# Generated by Django 4.1.5 on 2023-09-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0002_rename_image_user_profile_remove_user_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyloan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('pan', models.CharField(default='', max_length=20)),
                ('aadhar', models.CharField(default='', max_length=20)),
                ('amount', models.CharField(default='', max_length=20)),
                ('tenure', models.CharField(default='', max_length=3)),
                ('loanType', models.CharField(choices=[('PERSONAL LOAN', 'personal loan'), ('HOME LOAN', 'home loan'), ('EDUCATION LOAN', 'education loan'), ('CAR LOAN', 'car loan'), ('TWO WHEELER LOAN', 'two wheeler loan'), ('GOLD LOAN', 'gold loan'), ('PROPERTY LOAN', 'property loan')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='depositetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('FIXED DEPOSIT', 'fixed deposit'), ('RECURRING DEPOSIT', 'recurring deposit'), ('NRI FIXED DEPOSIT', 'nri fixed deposit'), ('SAFE DEPOSIT LOCKER', 'safee deposit locker')], default='', max_length=20)),
                ('city', models.CharField(choices=[('AGRA', 'agra'), ('AHMEDABAD', 'ahmedabad'), ('AJMER', 'ajmer'), ('ANAND', 'anand'), ('ANKLESHWAR', 'ankleshwar'), ('BANGALORE', 'banglore'), ('BELGAUM', 'belgum'), ('BHILWARA', 'bhilwara'), ('BHOPAL', 'bhopal'), ('BIAORA', 'biaora'), ('BURHANPUR', 'burhanpur'), ('CHANDIGARH', 'chandigarh'), ('CHENNAI', 'chennai'), ('CHITTORGARH', 'chittorgarh'), ('COIMBATORE', 'coimbatore'), ('DAVANGERE', 'davangere'), ('DEHRADUN', 'dehradun'), ('DELHI NCR', 'delhi ncr'), ('DHAR', 'dhar'), ('DHARWAD', 'dharwad'), ('ERODE', 'erode'), ('GOKAK', 'gokak'), ('GUNTUR', 'guntur'), ('HARDA', 'harda'), ('HARVERI', 'harveri'), ('HIMMATNAGER', 'himmatnager'), ('HUBLI', 'hubli'), ('HYDERABAD', 'hyderabad'), ('INDORE', 'indore'), ('JAIPUR', 'jaipur'), ('JALANDHAR', 'jalandhar'), ('JAMKHANDI', 'jamkhandi'), ('JODHPUR', 'jodhpur'), ('KAKINADA', 'kakinada'), ('KANPUR', 'kanpur'), ('KHANDWA', 'khandwa'), ('KHARGAONE', 'khargaone'), ('KOCHI', 'kochi'), ('KOLKATA', 'kolkata'), ('KOTA', 'kota'), ('LUCKNOW', 'lucknow'), ('LUDHIANA', 'ludhiana'), ('MADURAI MANDSAUR', 'madurai mandsaur'), ('MORBI', 'morbi'), ('MUMBAI', 'mumbai'), ('NAGPUR', 'nagpur'), ('NASHIK', 'nashik'), ('NEEMUCH', 'neemuch'), ('PANIPAT', 'panipat'), ('PATAN', 'patan'), ('PIPARIYA', 'pipariya'), ('PUNE', 'pune'), ('RAIPUR', 'raipur'), ('RAJAHMUNDRY', 'rajamundry'), ('RAJGARH', 'rajgarh'), ('RAJKOT', 'rajkot'), ('RATLAM', 'ratlam'), ('SALEM', 'salem'), ('SANAWAD', 'sanawad'), ('SURAT', 'surat'), ('TANUKU', 'tanuku'), ('TIRUPPUR', 'tiruppur'), ('UJJAIN', 'ujjain'), ('VADODARA', 'vadodata'), ('VAPI', 'vapi'), ('VIJAYWADA', 'vijaywada'), ('VIZAG', 'vizag')], default='', max_length=20)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='openaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=255)),
                ('accountType', models.CharField(choices=[('SAVING ACCOUNT', 'saving account'), ('CORPORATE SALARY ACCOUNT', 'corporate salary account'), ('SENIOR CITIZEN SAVING ACCOUNT', 'senior citizen saving account'), ('CURRENT ACCOUNT', 'current account'), ('NRI SAVING ACCOUNT', 'nri saving account')], default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('pan', models.CharField(default='', max_length=20)),
                ('aadhar', models.CharField(default='', max_length=20)),
                ('occupation', models.CharField(choices=[('DOCTOR', 'doctor'), ('ENGINEER', 'engineer'), ('BUSINESSMAN', 'businessman'), ('CHARTERED ACCOUNTANT', 'chartered accountant'), ('STUDENT', 'student')], default='', max_length=255)),
                ('incomeSource', models.CharField(choices=[('SALARY', 'salary'), ('BUSINESS', 'business'), ('STOCKS', 'stocks'), ('POCKET MONEY', 'pocket money'), ('RENT', 'rent')], default='', max_length=20)),
                ('grossAnnualIncome', models.CharField(default='', max_length=20)),
                ('mothersname', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
